Repository zooniverse/Panoptes-Front-End, pull requests merged in 2019-12, with the labels that each got.

#5558 Remove grid tool from list of experimental features
  app/pages/admin/project-status/experimental-features.jsx
Labels: experiments, refactor

#5575 Add css to change font-family for Czech
  css/typography.styl
Labels: design, translations

#5576 Remove https and open config options
  webpack.dev.js
Labels: bug

#5553 Ellipse region feedback
  app/features/feedback/shared/strategies/drawing/pointInEllipse/README.md
  app/features/feedback/shared/strategies/drawing/pointInEllipse/create-rule.js
  app/features/feedback/shared/strategies/drawing/pointInEllipse/create-rule.spec.js
  app/features/feedback/shared/strategies/drawing/pointInEllipse/feedback-mark.jsx
  app/features/feedback/shared/strategies/drawing/pointInEllipse/index.js
  app/features/feedback/shared/strategies/drawing/pointInEllipse/reducer.js
  app/features/feedback/shared/strategies/drawing/pointInEllipse/reducer.spec.js
  app/features/feedback/shared/strategies/index.js
Labels: enhancement

#5581 Add refresh for PHT home page
  app/router.cjsx
Labels: bug
