Repository zooniverse/Panoptes-Front-End, pull requests merged in 2019-06, with the labels that each got.

#5361 Add audio player min-width
  css/subject-viewer.styl
Labels: audio

#5363 Refactor dropdown task bug with option value of 0
  app/classifier/tasks/dropdown/index.jsx
  app/classifier/tasks/dropdown/index.spec.js
Labels: bug, classifier

#5394 Edit project home workflows request to initially filter on completeness
  app/pages/project/home/index.jsx
Labels: enhancement

#5376 Add state: live to project queries on home
  app/lib/get-social-data.js
Labels: bug

#5414 Set locale from project primary language
  app/pages/project/index.jsx
Labels: translations

#5407 Project Builder: Link to the production translation editor
  app/pages/lab/translations/index.jsx
  app/pages/lab/translations/translation-tools.jsx
Labels: translations

#5412 Add browser based validation for the real name field
  app/partials/register-form.cjsx
Labels: enhancement

#5420 Focus question task if have true autoFocus prop
  app/classifier/tasks/multiple/index.jsx
  app/classifier/tasks/single/index.jsx
Labels: bug, classifier
