Repository zooniverse/Panoptes-Front-End, pull requests merged in 2020-06, with the labels that each got.

#5727 npm audit fix
  package-lock.json
  package.json
Labels: security

#5730 Add translated content for hr and pt locales
  app/locales/hr.js
  app/locales/pt.js
Labels: translations

#5733 Update pt.js
  app/locales/pt.js
Labels: translations

#5739 Add museum role translation
  app/pages/project/about/team.jsx
Labels: bug
