Repository zooniverse/Panoptes-Front-End, pull requests merged in 2020-04, with the labels that each got.

#5671 Remove duplicates from the upcoming queue on append
  app/redux/ducks/classify.js
  app/redux/ducks/classify.spec.js
Labels: bug

#5667 Add a featured project editor to the Projects page
  app/pages/admin/project-status-list.jsx
  app/pages/projects/featured-project-editor.jsx
  app/pages/projects/project-filtering-interface.jsx
  app/pages/projects/projects-search-selector.jsx
  app/pages/projects/projects-welcome.jsx
  css/project-card.styl
Labels: enhancement

#5682 Edit survey task characteristics import for existing value change
  app/classifier/tasks/survey/editor.cjsx
Labels: bug, project builder

#5692 Add locales: hi, hn, ko
  app/constants/languageMenu.js
  app/locales/hi.js
  app/locales/index.js
  app/locales/kn.js
  app/locales/ko.js
Labels: translations
