Repository zooniverse/Panoptes-Front-End, pull requests merged in 2020-02, with the labels that each got.

#5606 Implemented false-positive mode for drawing strategy feedback
  app/features/feedback/classifier/components/feedback-modal.jsx
  app/features/feedback/classifier/helpers/feedback-categories.js
  app/features/feedback/classifier/helpers/open-feedback-modal.jsx
  app/features/feedback/classifier/helpers/open-feedback-modal.spec.js
  app/features/feedback/shared/strategies/drawing/column/README.md
  app/features/feedback/shared/strategies/drawing/column/create-rule.js
  app/features/feedback/shared/strategies/drawing/column/create-rule.spec.js
  app/features/feedback/shared/strategies/drawing/column/feedback-mark.jsx
  app/features/feedback/shared/strategies/drawing/pointInEllipse/README.md
  app/features/feedback/shared/strategies/drawing/pointInEllipse/create-rule.js
  app/features/feedback/shared/strategies/drawing/pointInEllipse/create-rule.spec.js
  app/features/feedback/shared/strategies/drawing/pointInEllipse/feedback-mark.jsx
  app/features/feedback/shared/strategies/drawing/pointInEllipse/reducer.js
  app/features/feedback/shared/strategies/drawing/radial/README.md
  app/features/feedback/shared/strategies/drawing/radial/create-rule.js
  app/features/feedback/shared/strategies/drawing/radial/create-rule.spec.js
  app/features/feedback/shared/strategies/drawing/radial/feedback-mark.jsx
  app/locales/en.js
  css/feedback.styl
Labels: enhancement

#5636 Register the Polish locale
  app/locales/index.js
Labels: translations

#5639 Fail gracefully when Google Analytics is not available
  app/lib/ga-log-adapter.js
  app/lib/ga-log-adapter.spec.js
Labels: bug
