Repository zooniverse/Panoptes-Front-End, pull requests merged in 2020-05, with the labels that each got.

#5702 Edit project home talk rtl translations
  app/locales/ar.js
  app/locales/he.js
Labels: bug, translations

#5704 add locale: hr
  app/constants/languageMenu.js
  app/locales/hr.js
  app/locales/index.js
Labels: translations

#5690 Fix talk tags page when navigating between projects
  app/router.cjsx
  app/talk/tags.cjsx
  app/talk/tags.jsx
  app/talk/tags.spec.js
Labels: bug

#5696 Refactor featured projects on home page
  app/pages/home-common/featured-project.jsx
  app/pages/home-common/featured-project.spec.js
  app/pages/home-common/featured-projects.jsx
  app/pages/home-common/featured-projects.spec.js
  app/pages/home-for-user/index.jsx
  app/pages/home-not-logged-in.jsx
Labels: design, ui

#5711 Fix organization researcher quote link
  app/pages/organization/organization-page.jsx
Labels: bug

#5706 Add translation for Field Guide toggle
  app/locales/ar.js
  app/locales/cs.js
  app/locales/de.js
  app/locales/en.js
  app/locales/es.js
  app/locales/fr.js
  app/locales/he.js
  app/locales/hi.js
  app/locales/it.js
  app/locales/ja.js
  app/locales/kn.js
  app/locales/ko.js
  app/locales/nl.js
  app/locales/pl.js
  app/locales/pt.js
  app/locales/sv.js
  app/locales/zh-cn.js
  app/locales/zh-tw.js
  app/pages/project/field-guide-container.jsx
Labels: translations
