Repository zooniverse/Panoptes-Front-End, pull requests merged in 2020-10, with the labels that each got.

#5803 Project admin: add workflow.grouped
  app/pages/admin/project-status.jsx
Labels: enhancement

#5819 Add Japanese locale file translations
  app/locales/ja.js
Labels: translations

#5795 Text task: fix potential infinite loop
  app/classifier/tasks/text/index.jsx
Labels: bug, refactor

#5830 Admin interface for subject viewer settings
  app/pages/admin/project-status.jsx
  app/pages/admin/project-status.spec.js
  css/admin-page.styl
Labels: enhancement

#5799 Talk: require a valid email address
  app/subjects/comment-form.cjsx
  app/talk/discussion-comment.jsx
  app/talk/discussion-comment.spec.js
Labels: enhancement, talk
