Repository zooniverse/Panoptes-Front-End, pull requests merged in 2020-09, with the labels that each got.

#5804 run npm audit
  package-lock.json
Labels: security

#5798 Expand user admin page
  app/lib/handle-input-change.coffee
  app/lib/handle-input-change.js
  app/pages/admin/user-settings/details.jsx
  app/pages/admin/user-settings/details.spec.js
Labels: enhancement

#5801 Full-size drawing tools: use subject dimensions
  app/classifier/drawing-tools/full-height-line.cjsx
  app/classifier/drawing-tools/full-width-line.cjsx
Labels: bug

#5821 Update babel
  babel.config.js
  package-lock.json
  package.json
Labels: dependencies
