Repository zooniverse/Panoptes-Front-End, pull requests merged in 2021-11, with the labels that each got.

#6040 Lab: Label unlabelled text inputs
  app/pages/lab/project-details.cjsx
  app/pages/lab/social-links-editor.jsx
  app/pages/lab/workflow.cjsx
  app/partials/display-name-slug-editor.jsx
Labels: bug, accessibility

#6046 Fix styling for video subject controls and survey task identifications
  css/subject-viewer.styl
Labels: bug

#6052 Update survey task editor link to templates
  app/classifier/tasks/survey/editor.cjsx
Labels: project builder

#6059 [Security] Remove request
  package-lock.json
  package.json
Labels: dependencies, security

#6056 Fix: allow deletion of Tasks whether or not they exist in Steps
  app/pages/lab-fem/workflow.cjsx
  app/pages/lab/workflow.cjsx
Labels: bug
