Repository zooniverse/Panoptes-Front-End, pull requests merged in 2021-03, with the labels that each got.

#5890 Add ur as rtl language, edit ur + hi translations
  app/locales/hi.js
  app/locales/ur.js
  app/redux/ducks/translations.js
Labels: translations

#5898 Add scatterPlot to the list in the admin pages
  app/pages/admin/project-status.jsx
Labels: enhancement

#5916 Use the thumbnail service for collections previews
  app/pages/collections/collection-card.jsx
Labels: collections

#5906 Add functionality to add or delete transcription task and steps
  app/pages/lab/workflow.cjsx
Labels: enhancement

#5917 Upgrade to node 14
  .travis.yml
  Dockerfile
  app/classifier/world-wide-telescope.spec.js
  package.json
Labels: dependencies

#5912 Update ar.js
  app/locales/ar.js
Labels: translations

#5913 Update he.js
  app/locales/he.js
Labels: translations

#5921 Change background-size to contain
  app/pages/collections/collection-card.jsx
Labels: collections, design

#5919 Use link to fe-project for transcription task workflows
  app/pages/lab/workflow.cjsx
Labels: enhancement
