Repository zooniverse/Panoptes-Front-End, pull requests merged in 2022-08, with the labels that each got.

#6165 Fix ProjectCreationForm modal to make responsive on smaller screens
  app/pages/lab/index.cjsx
Labels: ui

#6160 Add Turkish (tr) Locale
  app/constants/languageMenu.js
  app/locales/index.js
  app/locales/tr.js
Labels: translations

#6133 Upgrade redux and react-redux
  app/classifier/components/MinicourseButton/MinicourseButton.jsx
  app/classifier/components/MinicourseButton/MinicourseButton.spec.js
  app/classifier/components/TaskNavButtons/TaskNavButtons.spec.jsx
  app/classifier/components/TaskNavButtons/components/DoneButton/DoneButton.spec.jsx
  app/classifier/components/TaskNavButtons/components/NextButton/NextButton.spec.jsx
  app/classifier/components/TaskTabs/TaskTabs.spec.js
  app/classifier/components/TaskTabs/components/TutorialTab/TutorialTab.jsx
  app/classifier/components/TaskTabs/components/TutorialTab/TutorialTab.spec.js
  app/classifier/drawing-tools/components/DetailsSubTaskForm/DetailsSubTaskForm.jsx
  app/classifier/index.cjsx
  app/classifier/tasks/multiple/index.spec.js
  app/classifier/tasks/single/index.spec.js
  app/classifier/tasks/testHelpers/mockObjects.js
  app/pages/project/field-guide-container.jsx
  app/pages/project/field-guide-container.spec.jsx
  app/pages/project/index.jsx
  app/pages/project/project-page.spec.js
  app/redux/ducks/classify.js
  app/redux/ducks/translations.js
  package-lock.json
  package.json
Labels: dependencies

#6169 Pass initial loading state with the current user
  app/partials/app.cjsx
Labels: bug
