Repository zooniverse/Panoptes-Front-End, pull requests merged in 2022-05, with the labels that each got.

#6134 [Security] bump moment to 2.29.3
  package-lock.json
  package.json
Labels: dependencies, security

#6141 Bump panoptes-client to 3.4.1
  package-lock.json
  package.json
Labels: dependencies

#6135 [Security] Run `npm audit fix`
  package-lock.json
Labels: security

#6124 Fix subject counts for new subject sets
  app/pages/lab/subject-set.cjsx
Labels: bug

#6145 Add an optional locale to project page routes
  app/MonorepoRoutes.jsx
  app/pages/project/index.jsx
  app/router.jsx
Labels: translations

#6149 Use i18n routes for all project page paths.
  app/router.jsx
Labels: translations

#6147 Update page URL after changing language
  app/pages/project/components/LanguagePicker/LanguagePicker.jsx
  app/pages/project/components/LanguagePicker/LanguagePicker.spec.js
Labels: translations

#6143 Add description for survey task alwaysShowThumbnails
  app/classifier/tasks/survey/editor.cjsx
Labels: project builder, documentation

#6152 Use production API for staging
  .github/workflows/deploy_branch.yml
  .github/workflows/deploy_staging.yml
  package.json
Labels: ops
