Repository zooniverse/Panoptes-Front-End, pull requests merged in 2022-09, with the labels that each got.

#6173 Update ja Locale
  app/locales/ja.js
Labels: translations

#6195 Home page: Fix ‘Show all publications link’
  app/pages/home-common/social.jsx
Labels: bug

#6201 Bump Panoptes client to v4
  package-lock.json
  package.json
Labels: dependencies, security
