Repository zooniverse/Panoptes-Front-End, pull requests merged in 2022-10, with the labels that each got.

#6213 Bump panoptes-client from 4.1.1 to 4.2.0
  package-lock.json
  package.json
Labels: dependencies

#6215 Project builder: Fix undefined required tasks
  app/classifier/tasks/dropdown/index.jsx
  app/classifier/tasks/multiple/index.jsx
  app/classifier/tasks/single/index.jsx
  app/classifier/tasks/subjectGroupComparison/index.jsx
  app/classifier/tasks/survey/index.jsx
  app/classifier/tasks/textFromSubject/index.jsx
  app/pages/lab/workflow.cjsx
Labels: bug

#6217 Add required or not null properties for new workflow creation
  app/pages/lab/workflow-create-form.cjsx
Labels: bug, project builder

#6221 Fix broken survey task editor
  app/classifier/tasks/survey/editor.cjsx
Labels: bug
