Repository zooniverse/Panoptes-Front-End, pull requests merged in 2023-05, with the labels that each got.

#6553 Add check for grouped subject selection to mobile validations
  app/pages/lab/mobile/mobile-section-container.fixtures.js
  app/pages/lab/mobile/mobile-section-container.jsx
  app/pages/lab/mobile/mobile-section-container.spec.js
  app/pages/lab/mobile/mobile-section.jsx
Labels: bug, project builder, mobile

#6580 Add highlighter task default label color
  app/classifier/tasks/generic-editor.cjsx
Labels: bug, project builder

#6460 Add instruction input to survey task editor if using FEM lab
  app/classifier/tasks/survey/editor.cjsx
  app/pages/lab/workflow-components/task-editor.jsx
Labels: project builder

#6548 Refactor highlighter annotation end calculation
  app/classifier/tasks/highlighter/index.jsx
  app/classifier/tasks/highlighter/label-renderer.jsx
Labels: bug, classifier

#6603 Remove @sentry/tracing
  app/lib/init-sentry.js
  package-lock.json
  package.json
Labels: dependencies
