Repository zooniverse/Panoptes-Front-End, pull requests merged in 2023-08, with the labels that each got.

#6753 Add Indonesian to language menu
  app/constants/languageMenu.js
Labels: translations

#6755 Lab: Add instructions in Translations tab for new language
  app/pages/lab/translations/index.jsx
Labels: design, translations

#6786 Remove outdated Babel packages
  babel.config.js
  package-lock.json
  package.json
Labels: dependencies
