Repository zooniverse/Panoptes-Front-End, pull requests merged in 2023-02, with the labels that each got.

#6413 Handle errors on the Zooniverse social feed
  app/lib/get-social-data.js
  app/pages/home-common/social.jsx
Labels: bug, High Priority

#6417 Build with Node 18
  .github/workflows/ci-tests.yml
  .github/workflows/deploy_branch.yml
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
  Dockerfile
  package.json
Labels: ops

#6418 FEM Lab: build fem-version of multi-image subject options
  app/pages/lab-fem/components/fem-multi-image-subject-options-editor.jsx
  app/pages/lab-fem/workflow.jsx
Labels: enhancement

#6427 Log subject image errors to Sentry
  app/components/file-viewer/image-viewer.jsx
  app/main.cjsx
Labels: ops

#6438 Upgrade webpack-dev-server dependencies
  package-lock.json
Labels: dependencies
