Repository zooniverse/Panoptes-Front-End, pull requests merged in 2023-04, with the labels that each got.

#6491 Add JSON data subjects to recents
  app/components/file-viewer/canvas-viewer.jsx
  app/components/thumbnail.jsx
  app/features/modelling/line-plot/index.js
  app/pages/profile/recents.jsx
Labels: enhancement

#6514 Allow PDF, text and CSV media uploads
  app/lib/put-file.js
  app/pages/lab/actions/media.js
  app/pages/lab/media-area/media-area-view.jsx
  app/pages/lab/media.jsx
Labels: enhancement, security

#6536 FEM lab: Add separate frames layout options
  app/pages/lab-fem/components/fem-multi-image-subject-options-editor.jsx
Labels: project builder

#6538 Refactor highlighter task colors
  app/classifier/tasks/generic-editor.cjsx
Labels: project builder, design

#6541 Fix subject delete buttons in collections
  app/collections/show-list.jsx
Labels: bug
