Repository zooniverse/Panoptes-Front-End, pull requests merged in 2023-03, with the labels that each got.

#6457 Refactor image preloader, with Sentry logging
  app/classifier/annotation-renderer/svg.jsx
  app/classifier/annotation-renderer/text.jsx
  app/classifier/classifier.jsx
  app/classifier/frame-annotator.jsx
  app/classifier/world-wide-telescope.jsx
  app/collections/show-list.cjsx
  app/components/frame-viewer.jsx
  app/components/subject-viewer.cjsx
  app/lib/get-subject-location.coffee
  app/lib/getSubjectLocation.js
  app/lib/getSubjectLocations.js
  app/lib/load-image.coffee
  app/lib/loadImage.js
  app/lib/preload-subject.coffee
  app/lib/preloadSubject.js
  app/pages/profile/recents.jsx
  app/pages/project/home/project-home.jsx
  app/talk/comment-box.cjsx
  app/talk/comment-image-selector.cjsx
  app/talk/discussion-preview.cjsx
  app/talk/search-result.jsx
  app/talk/tags.jsx
Labels: refactor, ops

#6455 Remove host from webpack dev config
  README.md
  webpack.dev.js
Labels: documentation

#6454 FEM lab: add layout-options component
  app/pages/lab-fem/components/layout-options.jsx
  app/pages/lab-fem/workflow.jsx
Labels: project builder

#6458 Extend error logging for subject images
  app/classifier/classifier.jsx
  app/components/file-viewer/image-viewer.jsx
  app/lib/init-sentry.js
  app/lib/preloadSubject.js
  app/pages/project/index.jsx
Labels: refactor

#6461 Clarify name of property for displaying subject images with natural dimensions
  app/pages/lab-fem/components/layout-options.jsx
Labels: refactor

#6440 Add JSON subjects to Talk
  app/components/file-viewer/canvas-viewer.jsx
  app/features/modelling/line-plot/index.js
  app/pages/collections/collection-card.jsx
Labels: enhancement

#6466 Edit Feedback Docs
  app/features/feedback/README.md
Labels: documentation

#6480 FEM lab: Add layout option to limit subject height
  app/pages/lab-fem/components/layout-options.jsx
Labels: enhancement, project builder

#6479 Sanitise SVG file uploads
  app/lib/put-file.js
Labels: security

#6489 [Security] Sanitise SVG file uploads
  app/lib/put-file.js
Labels: security

#6516 Decaffeinate collection lists
  app/collections/show-list.cjsx
  app/collections/show-list.jsx
  app/collections/show.jsx
  app/router.jsx
Labels: bug, refactor
