Repository zooniverse/Panoptes-Front-End, pull requests merged in 2023-01, with the labels that each got.

#6286 Use default dependabot versioning strategy
  .github/dependabot.yml
Labels: dependencies, ops

#6351 Thumbnails: make height and width optional
  app/classifier/tasks/survey/chooser/Choices.jsx
  app/components/thumbnail.jsx
  app/pages/project/home/project-home.jsx
Labels: bug

#6375 Fix broken lab landing page
  css/landing-page.styl
  package-lock.json
  package.json
  webpack.build.js
  webpack.dev.js
Labels: bug, accessibility

#6382 Set panoptes-client to 4.2
  package-lock.json
  package.json
Labels: bug, High Priority

#6388 Fix moderator discussion board menu
  app/talk/discussion.cjsx
Labels: bug
