Repository zooniverse/Panoptes-Front-End, pull requests merged in 2025-05, with the labels that each got.

#7309 Refactor project error state messages
  app/pages/project/index.jsx
Labels: security

#7308 Rubin 2025 Landing Page pt1: duplicate /accounts page
  app/router.jsx
  app/rubin-2025/README.md
  app/rubin-2025/register-form.jsx
  app/rubin-2025/rubin-page.jsx
  app/rubin-2025/rubin-page.spec.js
  app/rubin-2025/sign-in-form.jsx
Labels: enhancement

#7311 Updated translations in existing dictionaries from Lokalise linguists
  app/locales/ar.js
  app/locales/bn.js
  app/locales/cs.js
  app/locales/de.js
  app/locales/es.js
  app/locales/fr.js
  app/locales/he.js
  app/locales/hi.js
  app/locales/hr.js
  app/locales/hu.js
  app/locales/hy.js
  app/locales/it.js
  app/locales/ja.js
  app/locales/nl.js
  app/locales/pl.js
  app/locales/pt.js
  app/locales/ru.js
  app/locales/sv.js
  app/locales/tr.js
  app/locales/ur.js
  app/locales/zh-cn.js
  app/locales/zh-tw.js
Labels: translations

#7315 Add new languages with hired translations May 2025
  app/constants/languageMenu.js
  app/constants/languages.js
  app/locales/da.js
  app/locales/el.js
  app/locales/fi.js
  app/locales/ha.js
  app/locales/id.js
  app/locales/index.js
  app/locales/kn.js
  app/locales/ko.js
  app/locales/mr.js
  app/locales/sw.js
  app/locales/te.js
  app/locales/uk.js
  app/locales/ve.js
  app/locales/vi.js
Labels: translations
